[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'

[[plugins]]
repo = 'folke/tokyonight.nvim'
source = 'main'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
lua << EOF
require'lspconfig'.gopls.setup{on_attach=require'completion'.on_attach}
EOF
'''

# auto complete
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
repo = 'hrsh7th/vim-vsnip-integ'


# Go
[[plugins]]
repo = 'nvim-lua/completion-nvim'

[[plugins]]
repo = 'mattn/vim-goimports'

# File Explore
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
lua << EOF
-- empty setup using defaults
require("nvim-tree").setup()

-- OR setup with some options
require("nvim-tree").setup({
  sort_by = "case_sensitive",
  view = {
    adaptive_size = true,
    mappings = {
      list = {
        { key = "u", action = "dir_up" },
      },
    },
  },
  renderer = {
    group_empty = true,
  },
  filters = {
    dotfiles = true,
  },
})
EOF
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
repo = 'lambdalisue/fern-git-status.vim'
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
# [[plugins]]
# repo = 'fatih/vim-go'
# hook_add = '''
#  " 保存時に必要なimportを自動的に挿入
#  let g:go_fmt_command = "goimports"
#  " LSPに任せる機能をOFFにする
#  let g:go_def_mapping_enabled = 0
#  let g:go_doc_keywordprg_enabled = 0
#'''
