[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'

[[plugins]]
repo = 'folke/tokyonight.nvim'
source = 'main'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
lua << EOF
require'lspconfig'.gopls.setup{}
EOF
'''

# Go
[[plugins]]
repo = 'nvim-lua/completion-nvim'


[[plugins]]
repo = 'lambdalisue/fern.vim'


[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
repo = 'lambdalisue/fern-git-status.vim'
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
# [[plugins]]
# repo = 'fatih/vim-go'
# hook_add = '''
#  " 保存時に必要なimportを自動的に挿入
#  let g:go_fmt_command = "goimports"
#  " LSPに任せる機能をOFFにする
#  let g:go_def_mapping_enabled = 0
#  let g:go_doc_keywordprg_enabled = 0
#'''
